# Generated by Django 4.2.2 on 2023-06-30 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discord_id', models.CharField(max_length=64)),
                ('leetcode_id', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_name', models.CharField(max_length=256)),
                ('problem_description', models.TextField()),
                ('difficulty_level', models.CharField(max_length=64)),
                ('problem_url', models.URLField()),
                ('times_chosen', models.IntegerField(default=0)),
                ('last_chosen', models.DateTimeField(null=True)),
                ('users_solved', models.ManyToManyField(related_name='problems_solved', to='catalog.user')),
            ],
        ),
    ]
