# Generated by Django 4.2.2 on 2023-06-30 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='problem_id',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
    ]
