# Generated by Django 4.2.2 on 2023-06-30 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_problem_problem_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='problem',
            table='leetcode_problems',
        ),
        migrations.AlterModelTable(
            name='user',
            table='discord_users',
        ),
    ]
