# Generated by Django 4.2.2 on 2023-06-30 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_problem_table_alter_user_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='users_solved',
        ),
        migrations.CreateModel(
            name='SolvedProblems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_solved', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.user')),
            ],
            options={
                'db_table': 'solved_problems',
                'unique_together': {('user', 'problem')},
            },
        ),
    ]
