# Generated by Django 4.2.2 on 2023-07-02 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_problem_users_solved_solvedproblems'),
    ]

    operations = [
        migrations.CreateModel(
            name='DifficultyPoints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'difficulty_points',
            },
        ),
        migrations.AddField(
            model_name='solvedproblems',
            name='solved_as_bounty_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='solvedproblems',
            name='solved_as_daily_challenge',
            field=models.BooleanField(default=False),
        ),
    ]
